#### 5.1.
1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

In [1]:
import numpy as np

In [2]:
m = np.array([1, 2, 3], float)
n = np.array([4, 5, 6], float)

In [3]:
print(f'm = {m}')
print(f'n = {n}')

m = [1. 2. 3.]
n = [4. 5. 6.]


In [4]:
# скалярное произведение
print(np.dot(m, n))
print(np.inner(m, n))

32.0
32.0


In [5]:
# векторное произведение
print(np.cross(m, n))

[-3.  6. -3.]


In [6]:
# смешанное произведение
print(np.dot(m, np.cross(m, n)))

0.0


2. Вычислите, по возможности не используя программирование: (5Е)-1, где Е – единичная матрица размера 5х5.

In [7]:
E = np.dot(1, np.identity(5))

In [8]:
print(E)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
A = np.dot(5, E)

In [10]:
print(A)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [11]:
A_inv = np.linalg.inv(A)

In [12]:
print(A_inv)

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


In [13]:
# проверка:
print(np.round(np.dot(A, A_inv), 0))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 5.2.
Вычислите определитель:
\begin{equation*}
\begin{vmatrix}
\mathbf{1} & \mathbf{2} & \mathbf{3} \\
\mathbf{4} & \mathbf{0} & \mathbf{6} \\
\mathbf{7} & \mathbf{8} & \mathbf{9}
\end{vmatrix}
\end{equation*}

In [14]:
M = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)

In [15]:
print(M)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [16]:
det_M = np.linalg.det(M)

In [17]:
print(np.round(det_M, 0))

60.0


#### 5.3.
1. Вычислите матрицу, обратную данной:
\begin{equation*}
\begin{vmatrix}
\mathbf{1} & \mathbf{2} & \mathbf{3} \\
\mathbf{4} & \mathbf{0} & \mathbf{6} \\
\mathbf{7} & \mathbf{8} & \mathbf{9}
\end{vmatrix}
\end{equation*}

In [18]:
G = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)

In [19]:
print(G)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [20]:
G_inv = np.linalg.inv(G)

In [21]:
print(G_inv)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [22]:
# проверка:
print(np.round(np.dot(G, G_inv), 0))

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


2. Приведите пример матрицы 4х4, ранг которой равен 1

In [23]:
v =np.array([1, 2, 3, 4])
F = np.array([v * 1, v * 2, v * 3, v * 4], float)

In [24]:
print(F)

[[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]


In [25]:
rank_F = np.linalg.matrix_rank(F)

In [26]:
print(rank_F)

1


#### 5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

In [27]:
a = np.array([1, 5], float)
b = np.array([2, 8], float)

In [28]:
print(f'a = {a}')
print(f'b = {b}')

a = [1. 5.]
b = [2. 8.]


In [29]:
ab = np.dot(a, b)

In [30]:
print(ab)

42.0


#### 5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

In [31]:
x = np.array([1, 5, 0], float)
y = np.array([2, 8, 7], float)
z = np.array([7, 1.5, 3], float)

In [32]:
print(f'x = {x}')
print(f'y = {y}')
print(f'z = {z}')

x = [1. 5. 0.]
y = [2. 8. 7.]
z = [7.  1.5 3. ]


In [33]:
xyz = np.dot(x, np.cross(y, z))

In [34]:
print(xyz)

228.5
